### ISSUE TITLE
When using this example to play the video below, it seems the video quality has degraded. Are there any parameters that can be configured to resolve this issue?

### ISSUE THREAD

**Issue by gubeils** [bilibili/web-demuxer#22]
https://foreversc.github.io/web-demuxer/#example-play
[test.zip](https://github.com/user-attachments/files/18032236/test.zip)

**Comment by ForeverSc** [comment]
In the example, I applied scaling to the canvas, which caused issues with the display of portrait videos because the scale was too small. You can manually adjust the canvas size and use dimensions that fit the video.
https://github.com/bilibili/web-demuxer/blob/main/index.html#L168-L169
