### ISSUE TITLE
对于被裁剪过的视频，seek 第一帧时获取到的是裁剪前的帧，而不是裁剪后的第一帧。

### ISSUE THREAD

**Issue by Reinhard2019** [bilibili/web-demuxer#23]
如下面这个视频，它之前前面被裁剪掉一部分，但 seek 时获取到的依然是裁剪前的第一帧。
https://github.com/user-attachments/assets/f797709f-8154-46d5-96f2-03d0c2613978

**Comment by ForeverSc** [comment]
视频开头的第一帧应该是裁剪的部分遗留的一个关键帧，seek默认后退寻址时，会被优先找到

**Comment by Reinhard2019** [comment]
> 视频开头的第一帧应该是裁剪的部分遗留的一个关键帧，seek默认后退寻址时，会被优先找到

这个问题似乎和 ffmpeg editlist 时间轴特性有关。不知道有没有方法可以解决。我之前用 mp4box.js 也有这个问题，但直接使用 ffmpeg 则是正常的。

**Comment by ForeverSc** [comment]
可以贴下具体ffmpeg使用的命令看下

**Comment by Reinhard2019** [comment]
> 可以贴下具体ffmpeg使用的命令看下

ffmpeg -ss 00:00:02  -to 00:00:04 -i input.mp4 -threads 2 -c copy output.mp4

**Comment by ForeverSc** [comment]
> > 视频开头的第一帧应该是裁剪的部分遗留的一个关键帧，seek默认后退寻址时，会被优先找到
> 
> 这个问题似乎和 ffmpeg editlist 时间轴特性有关。不知道有没有方法可以解决。我之前用 mp4box.js 也有这个问题，但直接使用 ffmpeg 则是正常的。 我原本以为 web-demuxer 底层也是用的 ffmpeg，能解决这个问题，不过还是存在。

想问的其实是这里提到的用ffmpeg seek截帧正常的命令，不是裁剪视频的命令哈
> 用 mp4box.js 也有这个问题，但直接使用 ffmpeg 则是正常的

**Comment by ForeverSc** [comment]
> > > > 视频开头的第一帧应该是裁剪的部分遗留的一个关键帧，seek默认后退寻址时，会被优先找到
> > > 
> > > 
> > > 这个问题似乎和 ffmpeg editlist 时间轴特性有关。不知道有没有方法可以解决。我之前用 mp4box.js 也有这个问题，但直接使用 ffmpeg 则是正常的。 我原本以为 web-demuxer 底层也是用的 ffmpeg，能解决这个问题，不过还是存在。
> > 
> > 
> > 想问的其实是这里提到的用ffmpeg seek截帧正常的命令，不是裁剪视频的命令哈
> > > 用 mp4box.js 也有这个问题，但直接使用 ffmpeg 则是正常的
> 
> 抱歉，搞错了。ffmpeg -i input.mp4 -vf "select=eq(n,0)" -vsync vfr output.png

视频本身时间戳是异常的，使用这个命令的话，视频帧实际已经被解码重排了，所以才能展示出视频0s的帧，而实际上原视频的第一帧就是web-demuxer例子中seek出来的那一帧。
web-demuxer是没有携带解码器的，目的也只是做解封装，所以这部分逻辑是没有的，只能靠自行实现做兼容了。

**Comment by Reinhard2019** [comment]
> > > > > 视频开头的第一帧应该是裁剪的部分遗留的一个关键帧，seek默认后退寻址时，会被优先找到
> > > > 
> > > > 
> > > > 这个问题似乎和 ffmpeg editlist 时间轴特性有关。不知道有没有方法可以解决。我之前用 mp4box.js 也有这个问题，但直接使用 ffmpeg 则是正常的。 我原本以为 web-demuxer 底层也是用的 ffmpeg，能解决这个问题，不过还是存在。
> > > 
> > > 
> > > 想问的其实是这里提到的用ffmpeg seek截帧正常的命令，不是裁剪视频的命令哈
> > > > 用 mp4box.js 也有这个问题，但直接使用 ffmpeg 则是正常的
> > 
> > 
> > 抱歉，搞错了。ffmpeg -i input.mp4 -vf "select=eq(n,0)" -vsync vfr output.png
> 
> 视频本身时间戳是异常的，使用这个命令的话，视频帧实际已经被解码重排了，所以才能展示出视频0s的帧，而实际上原视频的第一帧就是web-demuxer例子中seek出来的那一帧。 web-demuxer是没有携带解码器的，目的也只是做解封装，所以这部分逻辑是没有的，只能靠自行实现做兼容了。

好的，谢谢。
